// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMON_H_
#define FLATBUFFERS_GENERATED_COMMON_H_

#include "flatbuffers/flatbuffers.h"

struct fbVec;

struct EntityInfo;

enum class EntityFlag : int8_t {
  Player = 0,
  Monster = 1,
  Resource = 2,
  MIN = Player,
  MAX = Resource
};

inline const EntityFlag (&EnumValuesEntityFlag())[3] {
  static const EntityFlag values[] = {
    EntityFlag::Player,
    EntityFlag::Monster,
    EntityFlag::Resource
  };
  return values;
}

inline const char * const *EnumNamesEntityFlag() {
  static const char * const names[4] = {
    "Player",
    "Monster",
    "Resource",
    nullptr
  };
  return names;
}

inline const char *EnumNameEntityFlag(EntityFlag e) {
  if (flatbuffers::IsOutRange(e, EntityFlag::Player, EntityFlag::Resource)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesEntityFlag()[index];
}

enum class ErrorCode : uint16_t {
  None = 0,
  PacketError = 1,
  InValidSession = 2,
  InValidPos = 101,
  MIN = None,
  MAX = InValidPos
};

inline const ErrorCode (&EnumValuesErrorCode())[4] {
  static const ErrorCode values[] = {
    ErrorCode::None,
    ErrorCode::PacketError,
    ErrorCode::InValidSession,
    ErrorCode::InValidPos
  };
  return values;
}

inline const char *EnumNameErrorCode(ErrorCode e) {
  switch (e) {
    case ErrorCode::None: return "None";
    case ErrorCode::PacketError: return "PacketError";
    case ErrorCode::InValidSession: return "InValidSession";
    case ErrorCode::InValidPos: return "InValidPos";
    default: return "";
  }
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) fbVec FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  fbVec() {
    memset(static_cast<void *>(this), 0, sizeof(fbVec));
  }
  fbVec(float _x, float _y, float _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(fbVec, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) EntityInfo FLATBUFFERS_FINAL_CLASS {
 private:
  fbVec pos_;
  fbVec endpos_;
  float spd_;
  uint32_t table_id_;
  uint32_t entity_id_;
  int16_t angle_;
  int8_t flag_;
  int8_t padding0__;

 public:
  EntityInfo() {
    memset(static_cast<void *>(this), 0, sizeof(EntityInfo));
  }
  EntityInfo(const fbVec &_pos, const fbVec &_endpos, float _spd, uint32_t _table_id, uint32_t _entity_id, int16_t _angle, EntityFlag _flag)
      : pos_(_pos),
        endpos_(_endpos),
        spd_(flatbuffers::EndianScalar(_spd)),
        table_id_(flatbuffers::EndianScalar(_table_id)),
        entity_id_(flatbuffers::EndianScalar(_entity_id)),
        angle_(flatbuffers::EndianScalar(_angle)),
        flag_(flatbuffers::EndianScalar(static_cast<int8_t>(_flag))),
        padding0__(0) {
    (void)padding0__;
  }
  const fbVec &pos() const {
    return pos_;
  }
  const fbVec &endpos() const {
    return endpos_;
  }
  float spd() const {
    return flatbuffers::EndianScalar(spd_);
  }
  uint32_t table_id() const {
    return flatbuffers::EndianScalar(table_id_);
  }
  uint32_t entity_id() const {
    return flatbuffers::EndianScalar(entity_id_);
  }
  int16_t degree() const {
    return flatbuffers::EndianScalar(angle_);
  }
  EntityFlag flag() const {
    return static_cast<EntityFlag>(flatbuffers::EndianScalar(flag_));
  }
};
FLATBUFFERS_STRUCT_END(EntityInfo, 40);

#endif  // FLATBUFFERS_GENERATED_COMMON_H_
