// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PACKETS_H_
#define FLATBUFFERS_GENERATED_PACKETS_H_

#include "flatbuffers/flatbuffers.h"

enum class PacketId : uint16_t {
  ChatReq = 0,
  ChatAck = 1,
  ChatNfy = 2,
  EnterNeighborsNfy = 3,
  LeaveNeighborsNfy = 4,
  UpdateNeighborsNfy = 5,
  MoveReq = 6,
  MoveAck = 7,
  MoveNfy = 8,
  EnterWorldReq = 9,
  EnterWorldAck = 10,
  Debug3DPosition = 11,
  MIN = ChatReq,
  MAX = Debug3DPosition
};

inline const PacketId (&EnumValuesPacketId())[12] {
  static const PacketId values[] = {
    PacketId::ChatReq,
    PacketId::ChatAck,
    PacketId::ChatNfy,
    PacketId::EnterNeighborsNfy,
    PacketId::LeaveNeighborsNfy,
    PacketId::UpdateNeighborsNfy,
    PacketId::MoveReq,
    PacketId::MoveAck,
    PacketId::MoveNfy,
    PacketId::EnterWorldReq,
    PacketId::EnterWorldAck,
    PacketId::Debug3DPosition
  };
  return values;
}

inline const char * const *EnumNamesPacketId() {
  static const char * const names[13] = {
    "ChatReq",
    "ChatAck",
    "ChatNfy",
    "EnterNeighborsNfy",
    "LeaveNeighborsNfy",
    "UpdateNeighborsNfy",
    "MoveReq",
    "MoveAck",
    "MoveNfy",
    "EnterWorldReq",
    "EnterWorldAck",
    "Debug3DPosition",
    nullptr
  };
  return names;
}

inline const char *EnumNamePacketId(PacketId e) {
  if (flatbuffers::IsOutRange(e, PacketId::ChatReq, PacketId::Debug3DPosition)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPacketId()[index];
}

#endif  // FLATBUFFERS_GENERATED_PACKETS_H_
