// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PACKETS_H_
#define FLATBUFFERS_GENERATED_PACKETS_H_

#include "flatbuffers/flatbuffers.h"

enum class PacketId : int16_t {
  Chat_Req = 0,
  Chat_Resp = 1,
  Chat_Sync = 2,
  Sight_Sync = 3,
  Move_Sync = 4,
  MIN = Chat_Req,
  MAX = Move_Sync
};

inline const PacketId (&EnumValuesPacketId())[5] {
  static const PacketId values[] = {
    PacketId::Chat_Req,
    PacketId::Chat_Resp,
    PacketId::Chat_Sync,
    PacketId::Sight_Sync,
    PacketId::Move_Sync
  };
  return values;
}

inline const char * const *EnumNamesPacketId() {
  static const char * const names[6] = {
    "Chat_Req",
    "Chat_Resp",
    "Chat_Sync",
    "Sight_Sync",
    "Move_Sync",
    nullptr
  };
  return names;
}

inline const char *EnumNamePacketId(PacketId e) {
  if (flatbuffers::IsOutRange(e, PacketId::Chat_Req, PacketId::Move_Sync)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPacketId()[index];
}

#endif  // FLATBUFFERS_GENERATED_PACKETS_H_
