// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_WORLD_H_
#define FLATBUFFERS_GENERATED_WORLD_H_

#include "flatbuffers/flatbuffers.h"

#include "common_generated.h"

struct SightSync;
struct SightSyncBuilder;
struct SightSyncT;

struct SightSyncT : public flatbuffers::NativeTable {
  typedef SightSync TableType;
  std::vector<EntityInfo> entities;
  SightSyncT() {
  }
};

struct SightSync FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SightSyncT NativeTableType;
  typedef SightSyncBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTITIES = 4
  };
  const flatbuffers::Vector<const EntityInfo *> *entities() const {
    return GetPointer<const flatbuffers::Vector<const EntityInfo *> *>(VT_ENTITIES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ENTITIES) &&
           verifier.VerifyVector(entities()) &&
           verifier.EndTable();
  }
  SightSyncT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SightSyncT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<SightSync> Pack(flatbuffers::FlatBufferBuilder &_fbb, const SightSyncT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SightSyncBuilder {
  typedef SightSync Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_entities(flatbuffers::Offset<flatbuffers::Vector<const EntityInfo *>> entities) {
    fbb_.AddOffset(SightSync::VT_ENTITIES, entities);
  }
  explicit SightSyncBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  SightSyncBuilder &operator=(const SightSyncBuilder &);
  flatbuffers::Offset<SightSync> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SightSync>(end);
    return o;
  }
};

inline flatbuffers::Offset<SightSync> CreateSightSync(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<const EntityInfo *>> entities = 0) {
  SightSyncBuilder builder_(_fbb);
  builder_.add_entities(entities);
  return builder_.Finish();
}

inline flatbuffers::Offset<SightSync> CreateSightSyncDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<EntityInfo> *entities = nullptr) {
  auto entities__ = entities ? _fbb.CreateVectorOfStructs<EntityInfo>(*entities) : 0;
  return CreateSightSync(
      _fbb,
      entities__);
}

flatbuffers::Offset<SightSync> CreateSightSync(flatbuffers::FlatBufferBuilder &_fbb, const SightSyncT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline SightSyncT *SightSync::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<SightSyncT> _o = std::unique_ptr<SightSyncT>(new SightSyncT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SightSync::UnPackTo(SightSyncT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = entities(); if (_e) { _o->entities.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->entities[_i] = *_e->Get(_i); } } }
}

inline flatbuffers::Offset<SightSync> SightSync::Pack(flatbuffers::FlatBufferBuilder &_fbb, const SightSyncT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSightSync(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<SightSync> CreateSightSync(flatbuffers::FlatBufferBuilder &_fbb, const SightSyncT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const SightSyncT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _entities = _o->entities.size() ? _fbb.CreateVectorOfStructs(_o->entities) : 0;
  return CreateSightSync(
      _fbb,
      _entities);
}

#endif  // FLATBUFFERS_GENERATED_WORLD_H_
