// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PACKETS_H_
#define FLATBUFFERS_GENERATED_PACKETS_H_

#include "flatbuffers/flatbuffers.h"

enum class PacketId : int16_t {
  ChatReq = 0,
  ChatResp = 1,
  ChatSync = 2,
  EnterNeighborsSync = 3,
  LeaveNeighborsSync = 4,
  UpdateNeighborsSync = 5,
  MoveReq = 6,
  MoveResp = 7,
  MoveSync = 8,
  EnterWorldReq = 9,
  EnterWorldResp = 10,
  MIN = ChatReq,
  MAX = EnterWorldResp
};

inline const PacketId (&EnumValuesPacketId())[11] {
  static const PacketId values[] = {
    PacketId::ChatReq,
    PacketId::ChatResp,
    PacketId::ChatSync,
    PacketId::EnterNeighborsSync,
    PacketId::LeaveNeighborsSync,
    PacketId::UpdateNeighborsSync,
    PacketId::MoveReq,
    PacketId::MoveResp,
    PacketId::MoveSync,
    PacketId::EnterWorldReq,
    PacketId::EnterWorldResp
  };
  return values;
}

inline const char * const *EnumNamesPacketId() {
  static const char * const names[12] = {
    "ChatReq",
    "ChatResp",
    "ChatSync",
    "EnterNeighborsSync",
    "LeaveNeighborsSync",
    "UpdateNeighborsSync",
    "MoveReq",
    "MoveResp",
    "MoveSync",
    "EnterWorldReq",
    "EnterWorldResp",
    nullptr
  };
  return names;
}

inline const char *EnumNamePacketId(PacketId e) {
  if (flatbuffers::IsOutRange(e, PacketId::ChatReq, PacketId::EnterWorldResp)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPacketId()[index];
}

#endif  // FLATBUFFERS_GENERATED_PACKETS_H_
